package com.blogspot.devnip.lombok.superbuilder;

import lombok.Getter;
import lombok.experimental.SuperBuilder;

import java.time.LocalDate;
import java.util.List;

/**
 * Manager is a type of Employee
 */
@Getter
@SuperBuilder
public class Manager extends Employee {

    /**
     * Employees managed by the Manager
     */
    private final List<Employee> teamMembers;

    /**
     * Date on which this employee became Manager
     */
    private final LocalDate promotionDate;

    /**
     * Customizing builder methods. Rest of the builder code will be auto generated by Lombok.
     *
     * @param <C>
     * @param <B>
     */
    public static abstract class ManagerBuilder<C extends Manager, B extends ManagerBuilder<C, B>>
            extends EmployeeBuilder<C, B> {

        private LocalDate promotionDate;

        public B promotionDate(String dateStr) {
            this.promotionDate = LocalDate.parse(dateStr);
            return self();
        }
    }
}
