package com.blogspot.devnip.lombok.constructor;

import lombok.NonNull;
import lombok.RequiredArgsConstructor;

import java.time.LocalDate;

@RequiredArgsConstructor
public class ComplexObject {

    @NonNull
    public final String id;

    public final String name;

    public final LocalDate dateOfBirth;

    // Not part of constructor generated by RequiredArgsConstructor
    public String country;
}
