package com.blogspot.devnip.lombok.constructor;

import java.time.LocalDate;

public class SimpleObjectService {

    /**
     * Instantiate object using Lombok generate constructor with no parameters.
     *
     * @return
     */
    public static SimpleObject noArgsConstructor() {
        return new SimpleObject();
    }

    /**
     * Instantiate object using all argument constructor generated by Lombok.
     *
     * @return
     */
    public static SimpleObject allArgsConstructor() {
        return new SimpleObject("James Smith", LocalDate.now());
    }

    /**
     * Instantiate object using manually written constructor.
     *
     * @return
     */
    public static SimpleObject customConstructor() {
        return new SimpleObject("James Smith");
    }
}
